SELECT * FROM PETSALE
;
SELECT SUM(SALEPRICE) AS SUM_OF_SALEPRICE FROM PETSALE
;
SELECT MAX(QUANTITY) FROM PETSALE
;
SELECT AVG(SALEPRICE) FROM PETSALE
;
SELECT AVG(SALEPRICE/QUANTITY) FROM PETSALE WHERE ANIMAL = 'Dog'
;
SELECT ROUND(SALEPRICE) FROM PETSALE
;
SELECT LENGTH(ANIMAL) FROM PETSALE
;
SELECT UCASE(ANIMAL) FROM PETSALE
;
SELECT * FROM PETSALE WHERE LCASE(ANIMAL) = 'cat'
;
SELECT DISTINCT(UCASE(ANIMAL)) FROM PETSALE
;
SELECT DAY(SALEDATE) FROM PETSALE WHERE ANIMAL = 'Cat'
;
select COUNT(*) from PETSALE where MONTH(SALEDATE) = '05'
;
select (SALEDATE + 3 DAYS) from PETSALE
;
select (CURRENT DATE- SALEDATE) from PETSALE